### ISSUE TITLE
injector.resolveAndInstantiate is not a function (angular 2.0.0-rc.0)

### ISSUE THREAD

**Issue by jon301** [CodeSequence/store-saga#23]
Hi,

I'm getting the following error when using `installSagaMiddleware`
It looks like the injector we use is an ElementInjector and not a ReflectiveInjector (see screenshot)

```
ORIGINAL EXCEPTION: TypeError: injector.resolveAndInstantiate is not a function
ORIGINAL STACKTRACE:
TypeError: injector.resolveAndInstantiate is not a function
    at SagaRunner._run (http://localhost:4200/vendor/store-saga/runner.js:63:52)
    at SagaRunner.run (http://localhost:4200/vendor/store-saga/runner.js:78:14)
    at eval (http://localhost:4200/vendor/store-saga/runner.js:34:66)
    at Array.forEach (native)
    at new SagaRunner (http://localhost:4200/vendor/store-saga/runner.js:34:27)
    at DebugAppView.Object.defineProperty.get (TodoComponent_Host.template.js:87:69)
    at DebugAppView.Object.defineProperty.get (TodoComponent_Host.template.js:93:154)
    at DebugAppView._View_TodoComponent_Host0.injectorGetInternal (TodoComponent_Host.template.js:162:98)
    at DebugAppView.AppView.injectorGet (http://localhost:4200/vendor/@angular/core/src/linker/view.js:96:21)
    at DebugAppView.injectorGet (http://localhost:4200/vendor/@angular/core/src/linker/view.js:269:49)
```

![image](https://cloud.githubusercontent.com/assets/122108/15039191/2689328c-12ab-11e6-889a-c2312428e121.png)
- angular 2.0.0-rc.0
- ngrx/store 1.5.0
- store-saga 1.0.0-beta.11

**Comment by Merott** [comment]
@jon301 - Did you solve this?

**Comment by jon301** [comment]
Nope
Looks like this project has been ported to ngrx/effects
You should take a look at it

**Comment by Merott** [comment]
Considering that ngrx/effects isn't officially ready yet, I thought I'd try to stick with store-saga while trying to upgrade my app to Angular RC1. 

I'm upgrading an Ionic 2 app to Angular RC1, and I don't even know what else is broken apart from the ngrx store, considering that the app won't run. So, I was trying to avoid moving to ngrx/effects while other parts of the app are still potentially broken...

Well, I guess that's the price to pay for living on the edge 😜
